<?php
set_time_limit(0);
ini_set("memory_limit","500M");
include_once('bootstrap.php');
//Doctrine_Core::dropDatabases();
//Doctrine_Core::createDatabases();
$conn->setCollate('utf8_unicode_ci');
$conn->setCharset('utf8');
Doctrine_Core::createTablesFromModels('models');
?>
